### ISSUE TITLE
Suggestion regarding Mastodon API key

### ISSUE THREAD

**Issue by hardpenguin** [59de44955ebd/twitter-to-bsky#1]
The userscript UI asks for the API key instead of the access token. The instructions on the greasyfork.org explain that but not in detail. The matter is complicated by the fact this is how those fields are grouped in the Mastodon default interface:

![Screenshot_20231106_141822](https://github.com/59de44955ebd/twitter-to-bsky/assets/20478460/8f01eb1c-8ef8-49e7-9733-7043d685d302)

As a result, I only managed to succeed by inputting the right configuration on the third try.

Works like a charm on the latest Firefox + Linux + Violentmonkey! Thanks!

**Comment by 59de44955ebd** [comment]
Well, the "placerholder" previously said "Mastodon API Key (access token)", and the README explained in detail that you have to enter an access token and how to get it.
