### ISSUE TITLE
Further pre-define the settings pop-up window CSS style

### ISSUE THREAD

**Issue by hardpenguin** [59de44955ebd/twitter-to-bsky#2]
Using Firefox with dark theme, some text is unreadable:

![obraz](https://github.com/59de44955ebd/twitter-to-bsky/assets/20478460/f2819637-429c-4020-9198-2876378b09f5)

This can be avoided by pre-defining the colors used by this popup more precisely in the CSS part of the userscript (for example: keep the background white but also determine that the text has to be black).

**Comment by 59de44955ebd** [comment]
Thanks for the hint, I had simply forgotton to handle twitter in dark mode (since I don't use it myself). This is fied now in new version 0.11, see screenshot.
![dark-mode](https://github.com/59de44955ebd/twitter-to-bsky/assets/12278038/dea3bc9f-477c-46df-9e08-739b533ec775)
