### ISSUE TITLE
All user scripts disappeared (Firefox + ViolentMonkey)

### ISSUE THREAD

**Issue by AleksG3** [59de44955ebd/twitter-to-bsky#4]
при запуске браузера Firefox был просто убит на повал, запускаю  ViolentMonkey а он девственно чистый, как вернуть мои пользовательские скрипты

**Comment by 59de44955ebd** [comment]
Please keep the conversation in english, otherwise I can't support.

**Comment by AleksG3** [comment]
when launching the Firefox browser, I was just killed on the rampage, I run ViolentMonkey and it's clean, how to get my user scripts back

**Comment by 59de44955ebd** [comment]
I'm afraid this is the wrong place for this question. There is definetely nothing inside my little userscript, as you can check yourself, which could be responsible for "removing your previous userscripts", if that's what you assume. If you have such weird issues with Violentmonkey, I would suggest to post this here instead:
https://github.com/violentmonkey/violentmonkey/issues

**Comment by AleksG3** [comment]
Thank you for your prompt response and for your advice
