### ISSUE TITLE
Hashtag support for Blue Sky

### ISSUE THREAD

**Issue by CodyMKW** [59de44955ebd/twitter-to-bsky#5]
Blue Sky now has hashtags but when you type a hashtag on Twitter and cross post to Blue Sky using this script the hashtag isn't clickable

**Comment by 59de44955ebd** [comment]
Latest version v0.13 now has minimal BSKY hashtag support. It uses regex /#\w+/g to detect hashtags in tweets and convert them into "facets" arrays for BSKY, which should work ok as long as you only use english/western hashtags, but will definitely fail for non-western unicode hashtags. To support those as well, a much more complicated regex would be needed.
