### ISSUE TITLE
Failure to post

### ISSUE THREAD

**Issue by MyFuneral** [59de44955ebd/twitter-to-bsky#6]
not working since yesterday morning...

**Comment by hardpenguin** [comment]
Ditto here, @59de44955ebd please help 😢

It seems broken since Twitter changed its domain to x.com. Just adding another line to match new domain was not sufficient.

**Comment by hardpenguin** [comment]
Thank you very much for fixing! I see even 0.13 version of the script. Good job!

**Comment by MyFuneral** [comment]
Perfect my friend, you rocks 🤘🤘
