### ISSUE TITLE
Make the script work when posting by CTRL+ENTER

### ISSUE THREAD

**Issue by hardpenguin** [59de44955ebd/twitter-to-bsky#7]
I have a feature request. Crossposting works great when I click the button "Post" in the tweet/post window on Twitter. However, I like to speed things up and send a tweet by using CTRL+ENTER key shortcut. In this case, crossposting event by twitter-to-bsky userscript is not triggered.

Can you update it to address it? Thanks!

**Comment by 59de44955ebd** [comment]
I actually wasn't aware of the CTRL+ENTER key shortcut. I'm am/was a Twitter user since 2009, but I always used independant 3rd party Twitter clients, not the browser app - until Musk made this impossible. I'll have a look at it.

**Comment by 59de44955ebd** [comment]
Done, latest version v0.14 now also supports cross-posting via Ctrl+Enter

**Comment by hardpenguin** [comment]
You are the best <3

**Comment by hardpenguin** [comment]
I can confirm it works
